akka.javasdk.dev-mode.http-port = 9028

listmonk.smtp.host = "localhost"
listmonk.smtp.host = ${?LISTMONK_SMTP_HOST}
listmonk.smtp.port = 1025
listmonk.smtp.port = ${?LISTMONK_SMTP_PORT}
listmonk.smtp.username = ""
listmonk.smtp.username = ${?LISTMONK_SMTP_USERNAME}
listmonk.smtp.password = ""
listmonk.smtp.password = ${?LISTMONK_SMTP_PASSWORD}
listmonk.smtp.starttls = false

listmonk.send.default-batch-size = 50
listmonk.send.default-concurrency = 4
listmonk.send.default-message-rate-per-second = 10
listmonk.send.default-max-send-errors = 100
